-- 1. Symbol dimension: metadata for every monitored trading pair.
CREATE TABLE IF NOT EXISTS crypto_market.dim_symbol
(
    symbol String,
    exchange LowCardinality(String) DEFAULT 'binance',
    market_type LowCardinality(String) DEFAULT 'spot',
    base_asset String,
    quote_asset String,
    trading_status LowCardinality(String),
    price_precision UInt8,
    quantity_precision UInt8,
    updated_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(updated_at)
ORDER BY (exchange, market_type, symbol);


-- 2. Normalized aggregate trades from the Binance aggTrade stream.
CREATE TABLE IF NOT EXISTS crypto_market.fact_agg_trades
(
    schema_version UInt16 DEFAULT 1,
    exchange LowCardinality(String) DEFAULT 'binance',
    market_type LowCardinality(String) DEFAULT 'spot',
    symbol LowCardinality(String),
    agg_trade_id Int64,
    event_time DateTime64(3, 'UTC'),
    trade_time DateTime64(3, 'UTC'),
    price Decimal(38, 18),
    quantity Decimal(38, 18),
    quote_quantity Decimal(38, 18),
    taker_side LowCardinality(String),
    buyer_is_market_maker Bool,
    first_trade_id Int64,
    last_trade_id Int64,
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(3, 'UTC'),
    processed_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(processed_at)
PARTITION BY toDate(trade_time)
ORDER BY (symbol, trade_time, agg_trade_id)
TTL trade_time + INTERVAL 3 DAY DELETE
SETTINGS index_granularity = 8192;


-- 3. Throttled best bid/ask snapshots from the Binance bookTicker stream.
CREATE TABLE IF NOT EXISTS crypto_market.fact_quote_snapshots
(
    exchange LowCardinality(String) DEFAULT 'binance',
    market_type LowCardinality(String) DEFAULT 'spot',
    symbol LowCardinality(String),
    update_id Int64,
    snapshot_time DateTime64(3, 'UTC'),
    best_bid_price Decimal(38, 18),
    best_bid_quantity Decimal(38, 18),
    best_ask_price Decimal(38, 18),
    best_ask_quantity Decimal(38, 18),
    mid_price Decimal(38, 18),
    spread Decimal(38, 18),
    spread_percentage Decimal(38, 18),
    kafka_partition Int32,
    kafka_offset Int64,
    kafka_timestamp DateTime64(3, 'UTC'),
    processed_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(processed_at)
PARTITION BY toDate(snapshot_time)
ORDER BY (symbol, snapshot_time, update_id)
TTL snapshot_time + INTERVAL 3 DAY DELETE
SETTINGS index_granularity = 8192;


-- 4. OHLCV and market metrics calculated for each time window.
CREATE TABLE IF NOT EXISTS crypto_market.agg_market_candles
(
    symbol LowCardinality(String),
    interval LowCardinality(String),
    window_start DateTime64(3, 'UTC'),
    window_end DateTime64(3, 'UTC'),
    open_price Decimal(38, 18),
    high_price Decimal(38, 18),
    low_price Decimal(38, 18),
    close_price Decimal(38, 18),
    base_volume Decimal(38, 18),
    quote_volume Decimal(38, 18),
    trade_count UInt64,
    vwap Decimal(38, 18),
    buy_volume Decimal(38, 18),
    sell_volume Decimal(38, 18),
    buy_pressure Decimal(38, 18),
    sell_pressure Decimal(38, 18),
    volatility Decimal(38, 18),
    updated_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(updated_at)
PARTITION BY toYYYYMM(window_start)
ORDER BY (symbol, interval, window_start)
TTL window_start + INTERVAL 12 MONTH DELETE
SETTINGS index_granularity = 8192;


-- 5. Price, volume, spread and pressure alerts generated by the pipeline.
CREATE TABLE IF NOT EXISTS crypto_market.fact_market_alerts
(
    alert_id UUID DEFAULT generateUUIDv4(),
    symbol LowCardinality(String),
    alert_type LowCardinality(String),
    severity LowCardinality(String),
    event_time DateTime64(3, 'UTC'),
    interval LowCardinality(String),
    metric_name LowCardinality(String),
    metric_value Decimal(38, 18),
    threshold_value Decimal(38, 18),
    message String,
    created_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(created_at)
PARTITION BY toYYYYMM(event_time)
ORDER BY (symbol, event_time, alert_type, alert_id)
TTL event_time + INTERVAL 90 DAY DELETE
SETTINGS index_granularity = 8192;


-- 6. Spark micro-batch execution and data-quality statistics.
CREATE TABLE IF NOT EXISTS crypto_market.etl_batch_runs
(
    run_id UUID,
    query_name LowCardinality(String),
    batch_id Int64,
    started_at DateTime64(3, 'UTC'),
    finished_at Nullable(DateTime64(3, 'UTC')),
    messages_read UInt64,
    valid_rows UInt64,
    invalid_rows UInt64,
    processing_latency_ms UInt64,
    status LowCardinality(String),
    error_message Nullable(String),
    recorded_at DateTime64(3, 'UTC') DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(recorded_at)
PARTITION BY toYYYYMM(started_at)
ORDER BY (query_name, run_id, batch_id)
SETTINGS index_granularity = 8192;
